#!/usr/bin/env python3
# gov thin-link shim -- generated by `gov setup --here`; do not hand-edit.
# Delegates to the global install so this repo rides the machine-wide governor.
# Regenerate with `gov setup --here` if the global install moves.
import subprocess, sys
_GLOBAL = 'C:\\Users\\nlnic\\.claude\\gov\\gov.py'
sys.exit(subprocess.run([sys.executable, _GLOBAL, *sys.argv[1:]]).returncode)
